version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: ebook_db
    environment:
      MYSQL_ROOT_PASSWORD: asdfg032589
      MYSQL_DATABASE: ebook
      MYSQL_USER: ebook
      MYSQL_PASSWORD: mitc
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
